_rkcms_dashboard:
    path:     /backend/dashboard
    defaults: { _controller: 'Controller\Cms\DashboardController::showAction' }
    methods:  [GET]

_rkcms_show_pages:
    path:     /backend/page/collection/show
    defaults: { _controller: 'Controller\PageCollection\ShowPageCollectionController::showAction' }
    methods:  [GET]

_rkcms_pages_collection_approve:
    path:     /backend/page/collection/approve
    defaults: { _controller: 'Controller\PageCollection\ApprovePageController::approvePageAction' }
    methods:  [POST]

_rkcms_save_page:
    path:     /backend/page/save
    defaults: { _controller: 'Controller\Page\SavePageController::saveAction' }
    methods:  [POST]

_rkcms_save_site:
    path:     /backend/page/collection/save-all
    defaults: { _controller: 'Controller\PageCollection\SaveAllPagesController::saveAction' }
    methods:  [POST]

_rkcms_page_approve:
    path:     /backend/page/approve
    defaults: { _controller: 'Controller\Page\ApprovePageController::approveAction' }
    methods:  [POST]

_rkcms_page_publish:
    path:     /backend/page/publish
    defaults: { _controller: 'Controller\Page\PublishPageController::publishAction' }
    methods:  [POST]

_rkcms_page_hide:
    path:     /backend/page/hide
    defaults: { _controller: 'Controller\Page\HidePageController::hideAction' }
    methods:  [POST]

_rkcms_list_permalinks:
    path:     /backend/page/permalinks
    defaults: { _controller: 'Controller\Page\PermalinksController::listPermalinksAction' }
    methods:  [GET]

_rkcms_show_themes:
    path:     /backend/theme/show
    defaults: { _controller: 'Controller\Theme\ShowThemeController::showAction' }
    methods:  [GET]

_rkcms_start_from_theme:
    path:     /backend/theme/start
    defaults: { _controller: 'Controller\Theme\StartFromThemeController::startAction' }
    methods:  [POST]

_rkcms_save_theme:
    path:     /backend/theme/save
    defaults: { _controller: 'Controller\Theme\SaveThemeController::saveAction' }
    methods:  [POST]

_rkcms_connect_elfinder_media:
    path:     /backend/elfinder/media/connect
    defaults: { _controller: 'Controller\ElFinder\ElFinderMediaController::mediaAction' }

_rkcms_connect_elfinder_media:
    path:     /backend/elfinder/files/connect
    defaults: { _controller: 'Controller\ElFinder\ElFinderFilesController::filesAction' }

_rkcms_show_users:
    path:     /backend/users/show
    defaults: { _controller: 'Controller\Security\ShowUserController::showAction' }
    methods:  [GET]

_rkcms_save_user:
    path:     /backend/user/save
    defaults: { _controller: 'Controller\Security\SaveUserController::saveAction' }
    methods:  [POST]

_rkcms_save_queue:
    path:     /backend/queue/save
    defaults: { _controller: 'Controller\Queue\SaveQueueController::saveAction' }
    methods:  [POST]

